export const newsData = {
  title: "Latest  Highlights",
  link: "#",
  items: [
    {
      id: 1,
      category: "Industrial",
      title: "Particularly worth mentioning are Gulf Tunnelling Company",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/news1.jpg",
      link: "#",
      date: "05/15/2025", // MM/DD/YYYY
    },
    {
      id: 2,
      category: "Industrial",
      title: "News Name  Dummy Text ",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/n1.jpg",
      link: "#",
      date: "05/15/2025",
    },
    {
      id: 3,
      category: "Industrial",
      title: "News Name  Dummy Text ",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/n2.jpg",
      link: "#",
      date: "05/14/2025",
    },
    {
      id: 4,
      category: "Industrial",
      title: "News Name  Dummy Text ",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/n3.jpg",
      link: "#",
      date: "05/13/2025",
    },
    {
      id: 5,
      category: "Industrial",
      title: "News Name  Dummy Text ",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/n4.jpg",
      link: "#",
      date: "05/12/2025",
    },
    {
      id: 6,
      category: "Industrial",
      title: "News Name  Dummy Text ",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/n5.jpg",
      link: "#",
      date: "05/11/2025",
    },
    {
      id: 7,
      category: "Industrial",
      title: "News Name  Dummy Text ",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/n6.jpg",
      link: "#",
      date: "05/10/2025",
    },
    {
      id: 8,
      category: "Industrial",
      title: "News Name  Dummy Text ",
      description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
      image: "/assets/img/news/n6.jpg",
      link: "#",
      date: "05/10/2025",
    },
  ],
};
