export type QhseType = {
    metaTitle:string;
    metaDescription:string;
    firstSection:{
        mainTitle:string;
        subTitle:string;
        primaryColorText:string;
        description:string;
    },
    secondSection:{
        title:string;
        description:string;
        image:string;
        imageAlt:string;
        items:[{
            image:string;
            imageAlt:string;
            title:string;
        }]
    },
    thirdSection:{
        title:string;
        description:string;
        items:[{
            image:string;
            imageAlt:string;
            title:string;
        }]
    },
    forthSection:{
        title:string;
        description:string;
        items:[{
            thumbnail:string;
            thumbnailAlt:string;
            title:string;
            images:[{
                image:string;
                imageAlt:string;
            }]
        }]
    },
    fifthSection:{
        title:string;
        description:string;
        items:[{
            image:string;
            imageAlt:string;
            title:string;
            description:string;
        }]
    }
}