export type careerData = {
    metaTitle:string,
    metaDescription:string,
    firstSection:{
        pageTitle:string,
        description:string,
        image:string,
        imageAlt:string
    },
    secondSection:{
        mainTitle:string,
        subTitle:string
    },
    thirdSection:{
        title:string
    },
    departments:[{
        name:string
    }],
    locations:[{
        name:string
    }],
    openings:[{
        firstSection:{
            title:string,
            jobTitle:string,
            department:string,
            location:string,
            employmentType:string,
            slug:string
        },
        secondSection:{
            title:string,
            description:string
        },
        thirdSection:{
            title:string,
            description:string
        },
        forthSection:{
            title:string,
            description:string
        }
    }]
}
