export const homeData = {
  fourthSection: {
    title: "Area of Expertise",
    items: [
      {
        id: 1,
        title: "General Contracting",
        icon: "/assets/img/icons/general-contracting.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/general-contracting.jpg",
        slug: "",
      },
      {
        id: 2,
        title: "Design & Build",
        icon: "/assets/img/icons/design-build.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/design-build.jpg",
        slug: "",
      },
      {
        id: 3,
        title: "Civil & Structural Works",
        icon: "/assets/img/icons/civil-structureal-works.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/civil-structural-work.jpg",
        slug: "",
      },
      {
        id: 4,
        title: "Infrastructure Development",
        icon: "/assets/img/icons/infrastructure-development.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/infrastructure-development.jpg",
        slug: "",
      },
      {
        id: 5,
        title: "MEP Services",
        icon: "/assets/img/icons/mep-services.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/mep-services.jpg",
        slug: "",
      },
      {
        id: 6,
        title: "Project Management",
        icon: "/assets/img/icons/project-management.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/project-management.jpg",
        slug: "",
      },
      {
        id: 7,
        title: "Preconstruction Planning",
        icon: "/assets/img/icons/preconstruction-planning.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/preconstruction-planning.jpg",
        slug: "",
      },
      {
        id: 8,
        title: "Facility Management",
        icon: "/assets/img/icons/facility-management.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/facility-management.jpg",
        slug: "",
      },
      {
        id: 9,
        title: "Specialized Industrial Services",
        icon: "/assets/img/icons/specialized-industrial-services.svg",
        description: "The competitive market conditions and aggressive business environment in the UAE have driven the construction industry to adopt a highly professional and systematic approach towards project execution.",
        image: "/assets/img/home/area-of-expertise/specialized-industrial-services.jpg",
        slug: "",
      },
    ],
  },
  fifthSection: {
    title: "Our Diverse Sectors",
    items: [
      {
        id: 1,
        icon: "/assets/img/icons/commercial.svg",
        title: "Commercial",
        description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
        image: "/assets/img/sectors/commercial.jpg",
        slug: "#",
      },
      {
        id: 2,
        icon: "/assets/img/icons/industrial.svg",
        title: "Infrastructure",
        description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
        image: "/assets/img/sectors/infrastructure.jpg",
        slug: "#",
      },
      {
        id: 3,
        icon: "/assets/img/icons/infrastructure.svg",
        title: "Industrial",
        description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
        image: "/assets/img/sectors/industrial.jpg",
        slug: "#",
      },
      {
        id: 4,
        icon: "/assets/img/icons/realestate.svg",
        title: "Real Estate",
        description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
        image: "/assets/img/sectors/realestate.jpg",
        slug: "#",
      },
    ],
  },
  sixthSection: {
    title: "News",
    link: "#",
    items: [
      {
        id: 1,
        category: "industrial",
        title: "Particularly worth mentioning are Gulf Tunnelling Company",
        description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
        image: "/assets/img/news/news1.jpg",
        link: "#",
        date: "15-05-2025",
      },
      {
        id: 2,
        category: "industrial",
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
        image: "/assets/img/news/news1.jpg",
        link: "#",
        date: "15-05-2025",
      },
      {
        id: 3,
        category: "industrial",
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        description: "At GCC, teamwork, quality, service, and creativity drive our success. With over AED 200 million..",
        image: "/assets/img/news/news1.jpg",
        link: "#",
        date: "15-05-2025",
      },
    ],
  },
};