export const certificationsData = {
  title: "Awards and Certificates",
  awards: {
    title: "Awards & Recognitions",
    items: [
      {
        title: "HSE Excellence Award",
        info: "TAQA Water Solutions, 2024	",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "HSE Excellence Award",
        documentInfo: "TAQA Water Solutions, 2024	",
        category: "award",
      },
      {
        title: "Best Contractor – Infrastructure Development	",
        info: "UAE Contractors Council, 2023",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "Best Contractor – Infrastructure Development",
        documentInfo: "UAE Contractors Council, 2023",
        category: "award",
      },
      {
        title: "Safety Compliance Award	",
        info: "ADNOC Projects, 2023",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "Safety Compliance Award",
        documentInfo: "ADNOC Projects, 2023	",
        category: "award",
      },
      {
        title: "Innovation in Construction & Engineering Award",
        info: "Middle East Project Awards, 2021",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "Innovation in Construction & Engineering Award",
        documentInfo: "Middle East Project Awards, 2021",
        category: "award",
      },
      {
        title: "Outstanding Commitment to HSE Standards",
        info: "Abu Dhabi Municipality, 2020",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "Outstanding Commitment to HSE Standards",
        documentInfo: "Abu Dhabi Municipality, 2020",
        category: "award",
      },
    ],
  },
  certifications: {
    title: "ISO Certifications",
    items: [
      {
        title: "ISO 9001:2015",
        info: "GCC, 2024",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "ISO 9001:2015",
        documentInfo: "GCC, 2024",
        category: "certification",
      },
      {
        title: "ISO 14001:2015",
        info: "GCC, 2024",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "ISO 14001:2015",
        documentInfo: "GCC, 2024",
        category: "certification",
      },
      {
        title: "ISO 45001:2018",
        info: "GCC, 2024",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "ISO 45001:2018",
        documentInfo: "GCC, 2024",
        category: "certification",
      },
      {
        title: "ISO 50001:2018",
        info: "GCC, 2024",
        thumbnail: "/assets/img/certifications/doc-1-thumb.jpg",
        document: "/assets/img/certifications/doc-1.pdf",
        documentTitle: "ISO 50001:2018",
        documentInfo: "GCC, 2024",
        category: "certification",
      },
    ],
  },
};