export const blogData = {
  pageTitle: "Blog",
  bannerImg: "/assets/img/blog/bnr.jpg",
  items: [
    {
      id: 1,
      title: "How to Prevent Cost Overruns On-Site ?",
      image: "/assets/img/blog/blg-1.jpg",
      date: "05-16-2025",
      category: "Technology & Innovation",
    },
    {
      id: 2,
      title: "Understanding Gantt Charts in Planning.",
      image: "/assets/img/blog/blg-2.jpg",
      date: "05-17-2025",
      category: "Technology & Innovation",
    },
    {
      id: 3,
      title: "Role of QA/QC in Modern Construction Projects.",
      image: "/assets/img/blog/blg-3.jpg",
      date: "05-18-2025",
      category: "Technology & Innovation",
    },
    {
      id: 4,
      title: "How We Maintain Efficiency During Design-Build.",
      image: "/assets/img/blog/blg-4.jpg",
      date: "05-19-2025",
      category: "Project Updates",
    },
    {
      id: 5,
      title: "Smart Construction: Is IoT Changing the Game?",
      image: "/assets/img/blog/blg-5.jpg",
      date: "05-20-2025",
      category: "Technology & Innovation",
    },
    {
      id: 6,
      title: "Safety Audits: Why They’re More Than Just Checks?",
      image: "/assets/img/blog/blg-6.jpg",
      date: "05-21-2025",
      category: "Industry Blog",
    },
    {
      id: 7,
      title: "Sustainability Standards in GCC Projects.",
      image: "/assets/img/blog/blg-7.jpg",
      date: "05-22-2025",
      category: "Company Blog",
    },
    {
      id: 8,
      title: "BIM in Civil Construction: What to Know.",
      image: "/assets/img/blog/blg-8.jpg",
      date: "05-23-2025",
      category: "Company Blog",
    },
    {
      id: 9,
      title: "Equipment Spotlight: High-Performance Tunnel Boring.",
      image: "/assets/img/blog/blg-9.jpg",
      date: "05-24-2025",
      category: "Technology & Innovation",
    },
    {
      id: 10,
      title: "The Importance of Stakeholder Communication.",
      image: "/assets/img/blog/blg-10.jpg",
      date: "05-25-2025",
      category: "Project Updates",
    },
    {
      id: 11,
      title: "The Power of Precast in Infrastructure Builds.",
      image: "/assets/img/blog/blg-11.jpg",
      date: "06-05-2025",
      category: "Project Updates",
    },
    {
      id: 12,
      title: "How to Prevent Cost Overruns On-Site ?",
      image: "/assets/img/blog/blg-12.jpg",
      date: "06-05-2025",
      category: "Project Updates",
    },
  ],
};