import mongoose from "mongoose";

const aboutSchema = new mongoose.Schema({
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
    },
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    pageTitle:{
        type:String,
        required:true
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        },
    },
    secondSection:{
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            mainTitle:{
                type:String,
                required:true
            },
            subTitle:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    thirdSection:{
        primaryColourText:{
            type:String,
            required:true
        },
        title:{
            type:String,
            required:true
        },
        buttonText:{
            type:String,
            required:true
        }
    },
})

export default mongoose.models.AiTechnology || mongoose.model("AiTechnology", aboutSchema);