import mongoose from "mongoose";

const homeSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    bannerSection:{
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    numberSection:{
        items:[{
            number:{
                type:String,
                required:true
            },
            value:{
                type:String,
                required:true
            }
        }]
    },
    firstSection:{
        description:{
            type:String,
            required:true
        },
        buttonText:{
            type:String,
            required:true
        },
        video:{
            type:String,
            required:true
        },
        poster:{
            type:String,
            required:true
        },
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }],
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }],
    },
})

export default mongoose.models.Home || mongoose.model("Home", homeSchema);