import mongoose from "mongoose";

const qhseSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    firstSection:{
        mainTitle:{
            type:String,
            required:true
        },
        subTitle:{
            type:String,
            required:true
        },
        primaryColorText:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            }
        }]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            }
        }]
    },
    forthSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            thumbnail:{
                type:String,
                required:true
            },
            thumbnailAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            images:[{
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String,
                }
            }]
        }]
    },
    fifthSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }],
    },
})

export default mongoose.models.Qhse || mongoose.model("Qhse", qhseSchema);