import mongoose from "mongoose";

const sustainabilitySchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
    },
    pageTitle:{
        type:String,
        required:true
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            }
        }]
    },
    forthSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            }
        }]
    }
})

export default mongoose.models.Sustainability || mongoose.model("Sustainability", sustainabilitySchema);