import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "../globals.css";
import Header from "../components/common/Header";
import { ThemeProvider } from "next-themes";
import FooterV from "../components/common/FooterV";
import parse from "html-react-parser";
import Script from "next/script";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "GCC",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tagResponse = await fetch(`${process.env.BASE_URL}/api/admin/tags`);
  const tagData = await tagResponse.json();

  const navbarResponse = await fetch(`${process.env.BASE_URL}/api/admin/navbar`)
  const navbarData = await navbarResponse.json();

  const footerResponse = await fetch(`${process.env.BASE_URL}/api/admin/footer`)
  const footerData = await footerResponse.json();

  // Get the bodyScript safely
  const bodyScript = tagData?.tag?.bodyScript || "";

  // Decode URL-encoded quotes
  const decodedScript = bodyScript.replace(/%22/g, '"');

  // Extract inline JS and external script
  const inlineMatch = decodedScript.match(
    /<script>([\s\S]*?)<\/script>/
  );
  const externalMatch = decodedScript.match(
    /<script[^>]*src="([^"]+)"[^>]*><\/script>/
  );

  const inlineCode = inlineMatch ? inlineMatch[1] : "";
  const externalSrc = externalMatch ? externalMatch[1] : "";

  return (
    <html lang="en" suppressHydrationWarning>
      {tagData?.tag && (
        <head>{parse(tagData?.tag?.headerScript || "")}</head>
      )}
      <body className={`${dmSans.variable} antialiased`}>
        {/* Inline Zoho initialization */}
        {inlineCode && (
          <Script id="zoho-inline" strategy="afterInteractive">
            {inlineCode}
          </Script>
        )}

        {/* External Zoho script */}
        {externalSrc && (
          <Script
            id="zoho-external"
            src={externalSrc}
            strategy="afterInteractive"
            defer
          />
        )}

        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {navbarData.data.status == "published" && <Header data={navbarData.data} />}
          {children}
          {footerData.data.status == "published" && <FooterV data={footerData.data} />}
        </ThemeProvider>
      </body>
    </html>
  );
}
