import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "../globals.css";
import Header from "../components/common/Header";
import { ThemeProvider } from "next-themes";
// import { ScrollSmootherWrapper } from "../components/common/ScrollSmootherWrapper";
import FooterV from "../components/common/FooterV";
import parse from 'html-react-parser'

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "GCC",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const tagResponse = await fetch(`${process.env.BASE_URL}/api/admin/tags`);
  const tagData = await tagResponse.json();
  
  return (
    <html lang="en" suppressHydrationWarning>
      {tagData?.tag && <head>{parse(tagData?.tag?.headerScript || "")}</head>}
      <body className={`${dmSans.variable}  antialiased`}>
        {tagData?.tag && <>{parse(tagData?.tag?.bodyScript || "")}</>}
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {/* <ScrollSmootherWrapper> */}
          <Header />
          {children}
          <FooterV />
          {/* </ScrollSmootherWrapper> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
